//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildBirth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildBirth()
        {
            this.MedicalServiceRabbit = new HashSet<MedicalServiceRabbit>();
        }
    
        public int Id { get; set; }
        public int FemaleId { get; set; }
        public int MaleId1 { get; set; }
        public Nullable<int> MaleId2 { get; set; }
        public int ResultId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public System.DateTime StartDate1 { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public Nullable<System.DateTime> StartDate2 { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public System.DateTime ExpectBirthday { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Поле не может быть пустым")]
        public System.DateTime Birthday { get; set; }

        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalServiceRabbit> MedicalServiceRabbit { get; set; }
        public virtual Males Males { get; set; }
        public virtual Males Males1 { get; set; }
        public virtual Females Females { get; set; }
    }
}
