//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalServiceRabbit
    {
        public int Id { get; set; }
        public int RabbitId { get; set; }
        public int MedicalServiceId { get; set; }
    
        public virtual ChildBirth ChildBirth { get; set; }
        public virtual MedicalServices MedicalServices { get; set; }
    }
}
